- name: variables
  hosts: localhost
  vars:
   Student: "Akhil"
   Schedule: "evening"
  tasks: 
  - name: print information
    ansible.builtin.debug:
      msg: " Hi I am {{Student}} and will be joining meeting today {{Schedule}}"
